parameters:
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     test
    database_user:     test
    database_password: testpassword
    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~
    secret:            ThisTokenIsNotSoSecretChangeIt
    has_ssl: false
    directoki_read_only: false
    mailer_from_email: test@example.com
    mailer_from_name: test


